### ISSUE TITLE
InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by timabell** [wezeku/FixEFConcurrencyModes#1]
thanks for the utility, found it via http://stackoverflow.com/a/23345831/10245

I managed to break it :-)

```
FixEFConcurrencyModes\FixEFConcurrencyModes.exe -i ..\..\FooSystem\Db\FooModel.edmx

Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FixEFConcurrencyMode.setConcurrencyModeFixed@83.Invoke(EntityProperty entProp) in C:\repo\myclient\FixEFConcurrencyModes\FixEFConcurrencyModes\FixEFConcurrencyMode.fs:line 83
   at FixEFConcurrencyMode.fixCsdlConcurrencyModes(XElement csdl, IEnumerable`1 entProps) in C:\repo\myclient\FixEFConcurrencyModes\FixEFConcurrencyModes\FixEFConcurrencyMode.fs:line 89
   at FixEFConcurrencyMode.fixEdmxConcurrencyModes(CliOptions options) in C:\repo\myclient\FixEFConcurrencyModes\FixEFConcurrencyModes\FixEFConcurrencyMode.fs:line 109
   at FixEFConcurrencyMode.main(String[] argv) in C:\repo\myclient\FixEFConcurrencyModes\FixEFConcurrencyModes\FixEFConcurrencyMode.fs:line 142
```

which is here: https://github.com/wezeku/FixEFConcurrencyModes/blob/8b4d0c1427b16f3133cab6efdd0497e4109f28fb/FixEFConcurrencyModes/FixEFConcurrencyMode.fs#L83

I think the `.First()` isn't finding anything for some reason

**Comment by akasubi** [comment]
Could you mail me FooModel.edmx? (It seems that GitHub still doesn't hav a way to attach files.)

**Comment by timabell** [comment]
I'm afraid I can't as it's my client's code.

**Comment by akasubi** [comment]
I've just tried it on a couple of edmx files, but they don't trigger the problem so I can't reproduce it.

**Comment by timabell** [comment]
I'm not particularly familiar with f# so it's not immediately obvious to me what it's trying to read.

**Comment by akasubi** [comment]
Line 80 creates a collection of all Edmx/Runtime/ConceptualModels/Schema/EntityType entries. My guess is that the collection is empty. Is the edmx file edmx version 3.0 (2nd line in the edmx file)?

**Comment by timabell** [comment]
The edmx is indeed v3

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="3.0" xmlns:edmx="http://schemas.microsoft.com/ado/2009/11/edmx">
...
```

`entities` has lots of items in it when I debug and expand out enumerate the contents.

Ah I see what's going on, it's looking for `entProp.Entity` "Widgets" (plural) but `entities` contains one named "Widget" (singular) so it's not finding it.

**Comment by akasubi** [comment]
I took a shortcut and assumed that the SSDL EntityType names where the same as the CSDL EntityType names. I've changed that and updated the underlying EFConcurrencyModeTest to use the Mappings/EntityContainerMapping instead. Could you give the new version a try?

**Comment by timabell** [comment]
Sorry for the delay, just tried master on the edmx I'm working on and it worked a treat. Many thanks!
